### ISSUE TITLE
Ordering of Annotations in far right display pane

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#17]
Reported in JIRA as ANNO-57

Steps to recreate bug:
1) Go to an instance of the Annotation tool that already has annotations. 
2) Add a new annotation.
3) You will see that the newest annotation appears at the bottom of the right hand list. 
Expected behavior: The most recent annotation should appear at the top, since the ordering is Most reverse chronological order, with most recent items at the top.
Note, the only way I could trigger a reoder, was to navigate away from the tool, and come back.

It is expected that annotations in the new right hand pane are listed in reverse chronological order, with the most recent item at the top.   

However, when an annotation is first submitted, it appears at the bottom of the list.   The list doesn't get reordered until I navigate away from the page, and return.   (At which point the annotations are in the correct order).  

Please see attached screenshot, which shows the most recently added annotation at the bottom of the list.  

![screen shot 2015-09-03 at 10 55 43 am](https://cloud.githubusercontent.com/assets/2422354/9661943/14574bb2-522b-11e5-9115-e59967e885a2.png)

**Comment by lduarte1991** [comment]
In the mirador branch of my code I've been working with Rashmi to reorganize the dashboard code into three different components: logic controller (DashboardController.js), the view that handles displaying items (DashboardView.js) and the endpoint to annotator/catch/mirador which handles calls to the backend (AnnotationStoreController.js). I would take a look at the as this is not an issue with the tool there. I will be merging the mirador with master once we've made mirador work with the tool.

**Comment by arthurian** [comment]
Note: this is not an issue in the current release. However, we did tweak the ordering of replies so they are in chronological order as opposed to annotations, which are listed in reverse chronological order (per user feedback). See https://github.com/Harvard-ATG/annotationsx/pull/26

**Comment by arthurian** [comment]
This has been implemented in release [v1.0.4](https://github.com/Harvard-ATG/annotationsx/releases/tag/v1.0.4)
