### ISSUE TITLE
Ability to add instructions to an assignment

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#19]
(IN JIRA as ANNO-59)

The earlier version of AnnotationX had a place for instructors to post instructions along with text to be annotated.   This was removed intentionally as part of refactoring, with the plan to reintroduce the feature.  Since this will be a key feature for Lisa New's course, and also others, ATG will try to work on this, (with some guidance from Luis).

**Comment by arthurian** [comment]
Note: this feature is being worked on in the current sprint. See https://github.com/Harvard-ATG/annotationsx/pull/20.

**Comment by arthurian** [comment]
This has been implemented in release [v1.0.4](https://github.com/Harvard-ATG/annotationsx/releases/tag/v1.0.4).
