### ISSUE TITLE
Instructor not able to see dashboard until after navigating to annotation page (in Canvas) 

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#29]
(IN JIRA as ANNO-64)

There is an instructor using the tool in Canvas who cannot see the instructor dashboard on login. He must go to an assignment, scroll down on the right pane, at which point his student's annotaitons are visible, and when he returns to the home page, can then see the dashboard. 

(Can be recreated by proxying as instructor...)

**Comment by arthurian** [comment]
@ShannonRice When you have a moment, can you show me the issue again when you proxy? In particular, I'd like to inspect the parameters that are sent to the tool when it is first launched. 

The steps to do so are as follows (I can show you in person):

1. Navigate to the course in Canvas.
2. In the Chrome browser, press the following keys ```CMD + OPTION + J```. This should open the console. If not, you can always right-click on the page (anywhere) and select *Inspect Element*.
3. Click on the **Network** tab.
4. In the network tab, click on the **Doc** button (should be one of several filter options).
5. Click on the annotation tool in the course navigation.
6. In the network tab, you should see a request appear as "launch_lti/". Click on that.
7. On the request, click the "Headers" tab.
8. Copy & paste the request headers and/or take a screenshot.

**Comment by arthurian** [comment]
Note: this is working for the instructor now. Not sure what fixed it.
