### ISSUE TITLE
Unable to create annotation if "Allow Highlights" In the Annotator Settings.

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#33]
in JIRA as ANNO-70

This is a bug.  I set up a tool in Canvas, and when this box wasn't checked (which is the default) it would not display annotations in the right hand nav bar.  (I can create an annotation, an the next is highlighted where I selected, but the annotation doesn't display over on the right hand nav bar.

After checking that box, the tool works normally.

**Comment by arthurian** [comment]
Note: this should be fixed by https://github.com/Harvard-ATG/annotationsx/pull/39
