### ISSUE TITLE
Would like to be able to delete assignment. (currently users cannot)

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#34]
IN JIRA as  ANNO-102 

In the annotations tool, after I create an assignment, it is not clear if there is a way to remove the assignment. So if an instructor creates a few test annotation objects, they can not remove them.   

My current workaround is to move them to another course, that is not a production site, which makes that site become like a Trash Bin for sample annotation assignments.

**Comment by ShannonRice** [comment]
Actually, it looks like the way to accomplish this is to unnassociate all classes from the Assignment, by deselecting all courses, in the "Courses" tab.   (However, when I try to do this, I get an error, which I'll describe in a separate issue. )

**Comment by arthurian** [comment]
This is resolved with the new admin hub (can delete assignments).
