### ISSUE TITLE
Display issue with Firefox 

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#42]
when testing the latest Merge candidate in Canvas, the text is not displaying in Firefox. 

https://canvas.harvard.edu/courses/7145/external_tools/9703

Steps: 
1) Click on AnnotationsX
2) Look at list of assignments, click on "Dickensen Assginment"
3) This will show the list of objects, containing the poem "Ill tell you how the sun rose"
4) When I click on the poem title a blank screen appears and the poem does not display. (However, it displays fine in Chrome. )

**Comment by arthurian** [comment]
@ShannonRice This should be fixed now (just tested in Firefox). It was a configuration issue in our staging environment.

Basically, Firefox honors the [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) header while Chrome does not, and we hadn't configured it properly. It's basically a security feature to prevent rogue sites from being embedded in an iframe.
