### ISSUE TITLE
Unable to submit a "reply" to an existing annotation on an Image Assignment

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#45]
[Using Chrome] https://canvas.harvard.edu/courses/7145/external_tools/9703

I can annotate image assignments, however, When I submit a reply to any existing annotation, it doesn't seem to display. (I don't know if it is never saved, or just doesn't display) 

Steps:
1) Select an image assignment that already has comments
2) Click on a comment in the right hand pane
3) Click "reply"
4) A dialog box will open prompting you to submit text. Add your next and hit "save"
5) The dialog box closes, but there is no evidence of the reply having been saved.

**Comment by arthurian** [comment]
This should be fixed now and I've redeployed to staging.

For reference: https://github.com/lduarte1991/hx-annotations-lti/commit/e4829f3f3aa7b9110885299d30d72288ef5d66f1
