### ISSUE TITLE
Order of Assignments not maintained

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#50]
[Jira ANNO-87] cross-reference

The order of assignments is arbritrary.  It seems that it is ordered by last update, so making adjustments to assignments alters where they appear.   There should be a fixed chronological or reverse chronological order.   Alternately, (and this would be preferable...)  Is to allow the course administrator to drag and reorder assignments.

**Comment by arthurian** [comment]
This is resolved in the new admin hub (can reorder assignments, and the default order is preserved).
