### ISSUE TITLE
"Reply to Annotation" button should display higher.  Otherwise, very confusing.

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#51]
See JIRA ANNO-99
https://jira.huit.harvard.edu/browse/ANNO-99

The UI is currently confusing, for students attempting to reply to an annotation.   This could be alleviated by displaying the reply button higher on the screen.  See screenshot for details. 

Basically, it currently looks like you should type into the white space above the button, and then submit your reply. In actuality, you must hit the button (Which is partially hidden from view) and then you are prompted to submit a reply.  

Moving the location of the reply button to align at the top of the area would make this much easier to use. 

![button](https://cloud.githubusercontent.com/assets/2422354/11939912/21a07d20-a7f3-11e5-9177-56755e42cba5.png)

**Comment by arthurian** [comment]
Closing this issue because it should be fixed by https://github.com/lduarte1991/hxat/pull/55.
