### ISSUE TITLE
Unable to reply to lengthy text annotations

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#52]
[JIRA ANNO-98]

If an annotation is over a certain length, it becomes almost impossible to post a reply. (I haven't figured out the length, but it may be anything that fills the screen.  

In the attached example, I pasted the Gettysburg address as an annotation.  When attempting to submit a reply to that annotation, instead of the Reply button appearing, the annotation pane turns dark, and it is not possible to scroll down and see the Reply button.  

![longanno1](https://cloud.githubusercontent.com/assets/2422354/11942053/f5332f80-a801-11e5-963a-58b63d654a5a.png)

![longanno2](https://cloud.githubusercontent.com/assets/2422354/11942056/fa9c439e-a801-11e5-9ed0-9a9d6e29b3c8.png)

**Comment by arthurian** [comment]
Closing this issue because it should be fixed by https://github.com/lduarte1991/hxat/pull/55.
