### ISSUE TITLE
link to Manual not working properly

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#53]
![screen shot 2016-01-15 at 4 31 14 pm](https://cloud.githubusercontent.com/assets/2422354/12365880/aa478978-bba5-11e5-95ba-7b7bfbf0fc9f.png)
You can link to the manual.

I wonder if the wiki page name changed, and the link in AnnotationsX needs to be updated accordingly...

**Comment by arthurian** [comment]
I've update the URL to [this](https://wiki.harvard.edu/confluence/display/ANNOTATIONSX/AnnotationsX) and I also modified it so that it will open in a new window. Waiting for Luis to review the latter change (open in a new window) here: https://github.com/lduarte1991/hxat/pull/56

**Comment by arthurian** [comment]
This should be fixed now.
