### ISSUE TITLE
problem processing quotation marks

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#54]
[This appears to be a FIREFOX specific bug]

When an annotation starts with a quotation mark, it is incorrectly transformed into a '>' character.

I entered an annotation "The past is the past!" ......which became.......     "> "The past is the past!"

![screen shot 2016-01-15 at 4 39 24 pm](https://cloud.githubusercontent.com/assets/2422354/12366056/bf06eeca-bba6-11e5-849b-31ed1b9ae846.png)

**Comment by arthurian** [comment]
This appears to be fixed now (can reopen later if not).
