### ISSUE TITLE
Apparent text parsing issue in Instructor dashboard

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#66]
In the course taught by Daniel Donoghue (Arrivals Eng: 40) Canvas id 8845, there is a problem with anntoations displayed in the instructors dashboard.   Please see attached screenshot.  It appears that there are two entries at the top of the list with no associated student.  

(They were submitted by a student, but it looks like perhaps a problematic character broke the parsing? )

Please look into this and let me know.   

(Student names are smudged out, top row shows no student name appearing. )

![screenannox](https://cloud.githubusercontent.com/assets/2422354/15476279/1f274008-20dc-11e6-932a-777315359f51.jpg)

**Comment by arthurian** [comment]
I looked in the CATCH database to find those annotations, and it's very strange... there's no user ID or user name associated with those 2 annotations. In fact, the user made an annotation and then they must have noticed that their name was not attached to it, so they made a reply to their own annotation and wrote "by _username_" in the text field to fix it. Not quite sure how that could have happened, but at the very least it means that the instructor dashboard is not mishandling the user's name. 

I can't replicate this behavior, so I'd suggest we close this particular issue and open a new one if it comes up again.
