### ISSUE TITLE
When navigating to an assignment page from Instructor Dashboard, Annotations don't display

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#67]
Steps to recreate:

1) Go to the Instructor's dashboard screen of canvas site set up with the AnnotationsX tool that has active use from students. 

2) Click on a student's name that has one or more annotaitons recorded.  

3) Click on the hyperlinked text "Object".   

4) You will correctly be brought to the assignment.  However, the Annotations do not display, and the button to turn them on or off (x) or speech bubble icon do NOT appear, so there is no way to view annotations.  

I believe this to be a bug that was introduced in the latest release.

**Comment by arthurian** [comment]
Note: this should be fixed in the new admin hub (see PR https://github.com/lduarte1991/hxat/pull/73).

**Comment by arthurian** [comment]
Closing this issue since it should be fixed, but feel free to re-open if the issue persists.
