### ISSUE TITLE
Students logged in to the tool see the Admin buttons for “Create New Assignment” or “import from another course”

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#72]
Steps to recreate:  I (Shannon) set up my XID account as a “Guest” on the ATG demo site, and confirmed that I could See the buttons.  [EXPECTED BEHAVIOR: only instructors should have access to Create new Assignments]

[
![screen shot 2016-08-29 at 8 44 14 am](https://cloud.githubusercontent.com/assets/2422354/18052286/783383b8-6dc7-11e6-8cad-561ca3f92f6b.png)
](url)

When I clicked on “Create New Assignment” I received the following error: 
Not Found

The requested URL /accounts/login/ was not found on this server.

Rebecca also tested, in her case she masqueraded in Canvas as a real student, and when she clicked on “Create New Assignment” She WAS able to actually create a new assignment for the course (as a student). 

Note, the Instructor Dashboard correctly does not display when logged in as a student.

**Comment by arthurian** [comment]
This has been resolved by https://github.com/Harvard-ATG/annotationsx/releases/tag/v1.4.3.
