### ISSUE TITLE
Would be nice to be able to increase font size

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#85]
(from Caitlin Rajagopalan in Poetry in America) 
(also in JIRA as Anno-133: https://jira.huit.harvard.edu/browse/ANNO-133)

There is not a good way for a user to increase the font size if they have trouble reading.   (even zooming, doesn't work very well.)   Perhaps if we had a feature where a user could select larger font, that would help.

**Comment by arthurian** [comment]
This was fixed in release https://github.com/Harvard-ATG/annotationsx/releases/tag/v1.6.2
