### ISSUE TITLE
Currently not possible to edit source text once it's been input into an annotation object

### ISSUE THREAD

**Issue by ramiller84** [Harvard-ATG/annotationsx#86]
Reported by Caitlin Rajagopalan from "Poetry in America" course:

It doesn't currently seem to be possible to edit source text once it's been input into an annotation object.  It would be really helpful to have the ability to go back in and fix textual errors directly, rather than having to create an entirely new source text. 

See [#696 in Jira](https://jira.huit.harvard.edu/secure/RapidBoard.jspa?rapidView=95&view=planning&selectedIssue=ATGU-696&epics=visible&selectedEpic=ATGU-398).

**Comment by ramiller84** [comment]
This object does allow the source text to be edited:  Song of the Broad Axe (https://canvas.harvard.edu/courses/19515/modules/items/230070)

This object produces the source text as html: Song of Myself Sections 1 & 2  (https://canvas.harvard.edu/courses/19515/modules/items/230070)

**Comment by arthurian** [comment]
Questions:

1. What is a typical use case for this? For example, do you usually want to edit the source text while you're in the process of creating texts (students can't annotate them yet). Or, is the use case fixing a typo or something after students have started annotating?
2. If it's the second case, you want to edit a source text that already has annotations, how would you like this to be handled. Should we warn you, but allow you to make changes? Or not allow any changes at that point?

**Comment by arthurian** [comment]
This has been resolved in release https://github.com/Harvard-ATG/annotationsx/releases/tag/v1.6.5
